apiVersion: v1
kind: Pod
metadata:
  name: hp1
  labels: 
    app: test1
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80


---
apiVersion: v1
kind: Service
metadata: 
  name: hpsvc
spec: 
  type: LoadBalancer
  selector: 
    app: test1
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30088

  

