apiVersion: v1
kind: LimitRange
metadata: 
  name: limit1
  namespace: dell
spec:
  limits:
  - default: 
      cpu: "100m"
      memory: "500Mi"
    defaultRequest:
      cpu: "70m"
      memory: "256Mi"
    type: Container

