apiVersion: v1
kind: Namespace
metadata:
  name: eric2
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: eric2
spec:
  containers:
  - name: myapp-cont
    image: redis

