apiVersion: v1
kind: Pod
metadata:
  name: pod-on-node
  labels:
    app: myapp
    type: front-end
    tier: web
spec:
  containers:
   - name: app
     image: redis
  nodeName: node03
#  nodeSelector: 
#    type: ssd
