apiVersion: v1
kind: Pod
metadata:
  name: hpapp
  labels: 
    app: testapp
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80


---
apiVersion: v1
kind: Service
metadata: 
  name: myservice
spec: 
  type: NodePort
  selector: 
    app: testapp
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30777

  

